RMKIT_DIR = ../../resources/rmkit

font_test:
	cd $(RMKIT_DIR) && make font_test
	cp $(RMKIT_DIR)/src/build/font_test .

clean:
	rm -f font_test
	cd $(RMKIT_DIR) && make clean

.PHONY: font_test clean
